spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: app-url-shortener
    password: s3cr3t
    driver-class-name: org.postgresql.Driver

url-shortener:
  base-url: http://localhost:8080